### ISSUE TITLE
Is there a way to define optional argument?

### ISSUE THREAD

**Issue by floatdrop** [stretchr/over.js#2]
This library seems to be a pure fun, but have it optional arguments functionality? Like `function(name$string, options?object, callback$function)`?

**Comment by matryer** [comment]
You can do it with the `$etc` special argument name.

So if you wanted a function that took a string and optional number, you could do:

```
function(name$string, $etc)
```

That would match:

```
function("Mat")
```

and

```
function("Mat", 30)
```

BUT I like the idea that you can be explicit about the fact that it's an optional argument.  So, what about some of these interfaces:
1. Underscore after type means 'optional':
   
   `function(name$string, description$string_)`
2. Underscore before type means 'optional':
   
   `function(name$string, description$_string)`
3. Underscore before name means optional (nice because in your function body it will be clear that the argument is optional too):
   
   `function(name$string, _description$string)`
4. Dollar prefix means optional:
   
   `function(name$string, $description$string)`

What do you think?

**Comment by floatdrop** [comment]
Thank you for fast reply!

I would be very happy, if javascript can do things like this: `function withOpt(requires, [optional])`, so documentation will be identical to functional declaration. Or `?` from regular expressions. But it can't.

Therefore I suggest another variant: `function (required, options$$any)`, because of idea to keep modifiers close as possible (`$_` is fine to me too).

**Comment by floatdrop** [comment]
I close this one in favor for #3.
